url: sitot.ca
baseurl: ""

# Site settings
title: Sitôt Studio
email: info@sitot.ca
description: "Who you are deserves to be seen."


# Team names, titles and social links
people:
- name: Publications
  # pic: 1
  position: Research Lab Collabs
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Behind-the-scenes
  # pic: 2
  position: Short form videos
  social:
    - title: instagram
      url: #
    - title: tiktok
      url: #
    - title: linkedin
      url: #

- name: Completed Portraits
  # pic: 3
  position: View previous pieces
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  - title: linkedin
    url: http://linkedin.com/company/sitotstudio
  - title: instagram
    url: http://instagram.com/sitotstudio
  - title: github
    url: http://github.com/sitotstudio

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
