url: sitot.ca
baseurl: ""

# Site settings
title: Sitôt Studio
email: info@sitot.ca
description: Who you are deserves to be seen.


# Team names, titles and social links
people:
- name: Behind-the-scenes
  # pic: 1
  position: Short form videos
  social:
    - title: instagram
      url: http://instagram.com/sitotstudio
    - title: music
      url: http://tiktok.com/@sitotstudio
    - title: youtube
      url: https://youtube.com/@sitotstudio

- name: Completed Portraits
  # pic: 2
  position: View previous pieces
  social:
    - title: instagram
      url: http://instagram.com/sitotstudio
    - title: facebook
      url: http://facebook.com/sitotstudio
    - title: pinterest
      url: https://ca.pinterest.com/sitotstudio/_created

- name: Publications
  # pic: 3
  position: Research Lab Collabs
  social:
    - title: twitter
      url: https://x.com/sitotstudio
    - title: linkedin
      url: http://linkedin.com/company/sitotstudio
    - title: github
      url: http://github.com/sitotstudio

# Page Bottom Socials (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/company/sitotstudio
  - title: instagram
    url: http://instagram.com/sitotstudio
  - title: youtube
    url: https://youtube.com/@sitotstudio
  - title: pinterest
    url: https://ca.pinterest.com/sitotstudio/_created
  - title: facebook
    url: http://facebook.com/sitotstudio
  - title: music
    url: http://tiktok.com/@sitotstudio

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Sitemap
plugins:
  - jekyll-sitemap
